name: Build tcf-web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image and tag it with the commit hash
      - name: Build and tag the Docker image
        env:
          NEXT_PUBLIC_BACKEND_URL: "https://api.tcfgo.com/v1"
          NEXT_PUBLIC_ASSETS_DOMAIN: "https://assets.tcfgo.com"
        run: |
          docker build . --build-arg NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL --build-arg NEXT_PUBLIC_ASSETS_DOMAIN=$NEXT_PUBLIC_ASSETS_DOMAIN -t ${{ secrets.DOCKER_REPO }}/tcf-web:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_REPO }}/tcf-web:${{ github.sha }} ${{ secrets.DOCKER_REPO }}/tcf-web:latest

      # Step 5: Push the Docker image to Docker Hub (or your private registry)
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REPO }}/tcf-web:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REPO }}/tcf-web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: SSH into your server
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/deploy-scripts
            sh tcf-web.sh
